function report = otr_validate()
%OTR_VALIDATE Automated acceptance tests for the OTR reproduction.
%   REPORT = OTR_VALIDATE() runs deterministic, toolbox-free checks of the
%   analytical transmission-line model, temporal boundary conditions,
%   temporal slab, FFT utility, official source data, and a small MNA
%   circuit.  It writes
%       output/validation_report.mat
%       output/validation_summary.txt
%   beside this file. Any failed physical/numerical invariant raises an
%   assertion before a successful report is saved.
%
%   自动验收覆盖 SI S1--S3、S14--S17、守恒 beta 频率映射、时间板四路径、
%   负频谱、官方 source data 可读性，以及 MNA 的 ON/OFF 状态重映射和能量平衡。
%   The routine is directly runnable from any current working directory.

paths = otr_setup();
scriptDir = paths.reproduction;
outputDir = paths.output;

started = tic;
p = otr_parameters();
report = struct();
report.name = 'Observation of temporal reflection automated validation';
report.timestamp = char(datetime('now','Format','yyyyMMdd''T''HHmmss'));
report.matlabVersion = version;
report.status = 'running';
report.parameters = p;

%% SI S1: exact unit-cell matrix and unimodularity
[M100,abcd] = otr_abcd_unit_cell(p.fReference,'on','ideal',p);
theta = p.theta100;
b = p.b100;
expectedS1 = [ ...
    cos(theta)-0.5*b*sin(theta), ...
    1i*(sin(theta)+0.5*b*cos(theta)-0.5*b); ...
    1i*(sin(theta)+0.5*b*cos(theta)+0.5*b), ...
    cos(theta)-0.5*b*sin(theta)];
s1ElementError = max(abs(abcd.normalizedMatrix(:)-expectedS1(:)));
s1DeterminantError = abs(det(M100)-1);
normalizedDeterminantError = abs(det(abcd.normalizedMatrix)-1);
assert(s1ElementError < 1e-13,'otr:validate:S1Elements', ...
    'S1 element error %.3g exceeds tolerance.',s1ElementError);
assert(max(s1DeterminantError,normalizedDeterminantError) < 1e-12, ...
    'otr:validate:S1Determinant', ...
    'Unit-cell determinant error %.3g exceeds tolerance.',s1DeterminantError);
report.s1 = struct('elementMaxAbsError',s1ElementError, ...
    'determinantError',s1DeterminantError, ...
    'normalizedDeterminantError',normalizedDeterminantError,'passed',true);

%% SI S2/S3: Bloch trace identity and the reported 50 MHz impedance target
fBloch = [30 50 70]*1e6;
[betaOn,ZBOn,passOn,bloch] = otr_bloch_dispersion(fBloch,'on','ideal',p);
rhsS2 = cos(bloch.theta)-0.5*bloch.b.*sin(bloch.theta);
s2Error = max(abs(cos(betaOn*p.d)-rhsS2));
[~,ZBOff,passOff] = otr_bloch_dispersion(fBloch,'off','ideal',p);
zb50Error = abs(ZBOn(2)-p.Z0/2);
assert(all(passOn(:)) && all(passOff(:)),'otr:validate:S2PassBand', ...
    'The 30/50/70 MHz design samples must lie in the first pass bands.');
assert(s2Error < 1e-12,'otr:validate:S2Identity', ...
    'S2 trace error %.3g exceeds tolerance.',s2Error);
% The SI says exactly Z0/2, while its rounded theta=72 deg and b=2.753
% produce 24.949 ohm; a 0.1-ohm tolerance explicitly permits that rounding.
assert(zb50Error < 0.1,'otr:validate:S3DesignPoint', ...
    'S3 gives ZB(50 MHz)=%.6g ohm, not the reported 25-ohm target.',ZBOn(2));
assert(max(abs(ZBOff-p.Z0)) < 1e-10,'otr:validate:S3OffLine', ...
    'Unloaded Bloch impedance differs from Z0.');
report.s2s3 = struct('traceMaxAbsError',s2Error, ...
    'ZBon50Ohm',real(ZBOn(2)),'ZBon50TargetErrorOhm',zb50Error, ...
    'ZBoffOhm',real(ZBOff),'passed',true);

%% Fixed-beta frequency maps: ideal and practical series-RLC loads
fInput = [30 50 70]*1e6;
[fIdeal,betaIdeal,mapIdeal] = otr_frequency_map( ...
    fInput,'off','on','ideal',p);
[fIdealBack,~,mapIdealBack] = otr_frequency_map( ...
    fIdeal,'on','off','ideal',p);
[fRealistic,betaRealistic,mapRealistic] = otr_frequency_map( ...
    fInput,'off','on','realistic',p);
[fRealisticBack,~,mapRealisticBack] = otr_frequency_map( ...
    fRealistic,'on','off','realistic',p);
idealExpectedMHz = [16.74757769 27.77041234 38.57155812];
idealReferenceError = max(abs(fIdeal/1e6-idealExpectedMHz));
idealRoundtrip = max(abs(fIdealBack-fInput));
realisticRoundtrip = max(abs(fRealisticBack-fInput));
assert(idealReferenceError < 2e-6,'otr:validate:IdealMapReference', ...
    'Ideal fixed-beta map changed by %.3g MHz.',idealReferenceError);
assert(max(abs(mapIdeal.residualBeta)) < 1e-10 && ...
    max(abs(mapRealistic.residualBeta)) < 1e-10, ...
    'otr:validate:MapMomentum','A forward frequency map does not conserve beta.');
assert(max(abs(mapIdealBack.residualBeta)) < 1e-10 && ...
    max(abs(mapRealisticBack.residualBeta)) < 1e-10, ...
    'otr:validate:MapMomentumBack','A reverse frequency map does not conserve beta.');
assert(idealRoundtrip < 1 && realisticRoundtrip < 1, ...
    'otr:validate:MapRoundtrip','Frequency-map roundtrip exceeds 1 Hz.');
assert(all(fIdeal < fInput) && all(fRealistic < fInput), ...
    'otr:validate:MapDirection','OFF-to-ON mapping must redshift all test points.');
report.frequencyMap = struct('inputMHz',fInput/1e6, ...
    'idealOutputMHz',fIdeal/1e6,'realisticOutputMHz',fRealistic/1e6, ...
    'idealBeta',betaIdeal,'realisticBeta',betaRealistic, ...
    'idealRoundtripMaxHz',idealRoundtrip, ...
    'realisticRoundtripMaxHz',realisticRoundtrip,'passed',true);

%% SI S14--S17: microscopic ON/OFF laws and four coefficient identities
[Jon,Ton,Ron,onInfo] = otr_temporal_interface(50,25,'charge');
[Joff,Toff,Roff,offInfo] = otr_temporal_interface(25,50,'voltage');
coefficientError = max(abs([Ton Ron Toff Roff]-[0.375 -0.125 1.5 -0.5]));
identityResidual = [Ton+Ron-0.25, Ton-Ron-0.5, ...
    Toff+Roff-1, Toff-Roff-2];
matrixSymmetryError = max([norm(Jon-Jon.','fro'),norm(Joff-Joff.','fro')]);
assert(strcmp(onInfo.equation,'S14/S16') && strcmp(offInfo.equation,'S15/S17'), ...
    'otr:validate:InterfaceLaw','Temporal-interface law/equation labels are inconsistent.');
assert(coefficientError < 1e-14,'otr:validate:InterfaceCoefficients', ...
    'S16/S17 coefficient error %.3g exceeds tolerance.',coefficientError);
assert(max(abs(identityResidual)) < 1e-14,'otr:validate:InterfaceIdentities', ...
    'One of the four S16/S17 identities failed.');
assert(Ron < 0 && Roff < 0 && Ton > 0 && Toff > 0, ...
    'otr:validate:InterfaceSigns','Temporal-interface path signs are incorrect.');
report.temporalInterface = struct('Ton',Ton,'Ron',Ron,'Toff',Toff, ...
    'Roff',Roff,'identityResiduals',identityResidual, ...
    'matrixSymmetryError',matrixSymmetryError,'passed',true);

%% Temporal slab: matrix/path decomposition and first reflection zero
tau = 15e-9;
fSlab = linspace(1,100,19801)*1e6;
omegaSlab = 2*pi*(25/50)*fSlab;
[Sslab,pathsSlab] = otr_temporal_slab(50,25,tau,omegaSlab);
pathError = max([max(abs(pathsSlab.identityResidualForward(:))), ...
    max(abs(pathsSlab.identityResidualReflected(:)))]);
matrixReflection = reshape(Sslab(2,1,:),size(fSlab));
pathReflectionError = max(abs(matrixReflection-pathsSlab.timeReflected));
% Rslab = 2*a*cos(phi) here, so the first non-zero null is phi=pi/2.
fZeroTheory = 1/(4*(25/50)*tau);
zeroWindow = fSlab >= 0.75*fZeroTheory & fSlab <= 1.25*fZeroTheory;
candidate = find(zeroWindow);
[minimumReflection,localIndex] = min(abs(pathsSlab.timeReflected(candidate)));
fZeroNumeric = fSlab(candidate(localIndex));
zeroFrequencyError = abs(fZeroNumeric-fZeroTheory);
assert(pathError < 1e-12 && pathReflectionError < 1e-12, ...
    'otr:validate:SlabPaths','Temporal-slab four-path decomposition failed.');
assert(zeroFrequencyError < mean(diff(fSlab))+1, ...
    'otr:validate:SlabZero','First slab zero is not at the analytic frequency.');
assert(minimumReflection < 1e-4,'otr:validate:SlabNullDepth', ...
    'First temporal-slab reflection minimum is too shallow.');
report.temporalSlab = struct('tauNs',tau*1e9, ...
    'pathMaxAbsError',pathError,'firstZeroTheoryMHz',fZeroTheory/1e6, ...
    'firstZeroNumericMHz',fZeroNumeric/1e6, ...
    'minimumReflectionAmplitude',minimumReflection,'passed',true);

%% FFT: calibrated real amplitude and explicit negative-frequency peak
fs = 1e9;
t = (0:999)'/fs;
realTone = cos(2*pi*50e6*t);
[fReal,XReal] = otr_fft_spectrum(t,realTone);
[realPeak,realIndex] = max(abs(XReal));
complexTone = exp(-1i*2*pi*70e6*t);
[fComplex,XComplex] = otr_fft_spectrum(t,complexTone);
[complexPeak,complexIndex] = max(abs(XComplex));
assert(abs(fReal(realIndex)-50e6) < 1 && abs(realPeak-1) < 1e-12, ...
    'otr:validate:FFTAmplitude','One-sided FFT frequency/amplitude scaling failed.');
assert(abs(fComplex(complexIndex)+70e6) < 1 && abs(complexPeak-1) < 1e-12, ...
    'otr:validate:FFTNegative','Centered FFT failed to identify -70 MHz.');
report.fft = struct('realPeakMHz',fReal(realIndex)/1e6, ...
    'realPeakAmplitude',realPeak,'complexPeakMHz',fComplex(complexIndex)/1e6, ...
    'complexPeakAmplitude',complexPeak,'passed',true);

%% Official Nature source data: required files and finite numeric contents
dataDir = fullfile(scriptDir,'data','Time_Interface_Source_Data');
zipFile = fullfile(scriptDir,'source_data.zip');
dataPresent = exist(dataDir,'dir') == 7;
zipPresent = exist(zipFile,'file') == 2;
source = struct('dataDirectoryPresent',dataPresent,'zipPresent',zipPresent, ...
    'checkedFiles',{{}},'rowCounts',[],'columnCounts',[],'passed',false);
assert(dataPresent && zipPresent,'otr:validate:SourceArchive', ...
    ['The complete reproduction requires both source_data.zip and its ' ...
     'extracted data/Time_Interface_Source_Data directory.']);
if dataPresent
    relativeFiles = { ...
        fullfile('1e_raw','switch_off_Sim.txt'), ...
        fullfile('1e_raw','switch_on_Sim.txt'), ...
        fullfile('2e','freq_conv.csv'), ...
        fullfile('2f','freq_conv_reverse.csv')};
    source.checkedFiles = relativeFiles;
    source.rowCounts = zeros(1,numel(relativeFiles));
    source.columnCounts = zeros(1,numel(relativeFiles));
    for k = 1:numel(relativeFiles)
        filename = fullfile(dataDir,relativeFiles{k});
        assert(exist(filename,'file') == 2,'otr:validate:SourceFile', ...
            'Missing official source-data file: %s',filename);
        table = otr_read_numeric_table(filename);
        assert(~isempty(table.data) && size(table.data,2) >= 2 && ...
            all(any(isfinite(table.data),2)), 'otr:validate:SourceNumeric', ...
            'Official source-data file is not numerically readable: %s',filename);
        source.rowCounts(k) = size(table.data,1);
        source.columnCounts(k) = size(table.data,2);
    end
    redSweep = otr_read_numeric_table(fullfile(dataDir,'2e','freq_conv.csv'));
    blueSweep = otr_read_numeric_table(fullfile(dataDir,'2f','freq_conv_reverse.csv'));
    assert(size(redSweep.data,1)==9 && size(redSweep.data,2)>=4 && ...
        size(blueSweep.data,1)==6 && size(blueSweep.data,2)>=4, ...
        'otr:validate:SourceSweepShape','Official frequency-sweep table shape changed.');
    assert(all(diff(redSweep.data(:,1))>0) && all(diff(blueSweep.data(:,1))>0), ...
        'otr:validate:SourceSweepOrder','Official input frequencies are not increasing.');
    source.redshiftSweepMHz = redSweep.data(:,1:4);
    source.blueshiftSweepMHz = blueSweep.data(:,1:4);
    source.passed = true;
end
report.sourceData = source;

%% Small MNA smoke test: S14/S15 state maps plus discrete energy balance
mnaOptions = struct('physicsMode','ideal-capacitance','nCells',1, ...
    'includeParasitics',false,'Rseries',0,'Gshunt',0);
model = otr_build_mna(mnaOptions);
tMna = [0 1e-12 2e-12];
xInitial = zeros(model.nState,1);
xInitial(model.index.voltage) = [0.2;1.0];
scheduleOn = otr_switch_schedule(tMna,struct('nSwitch',model.nSwitches, ...
    'eventTimes',tMna(2),'states',[0 1]));
simOn = otr_simulate_circuit(model,tMna,0,scheduleOn, ...
    struct('initialState',xInitial));
eventOn = simOn.eventRecords(1);
lineCurrentJumpOn = norm(eventOn.statePlus(model.index.lineCurrent)- ...
    eventOn.stateMinus(model.index.lineCurrent),inf);

scheduleOff = otr_switch_schedule(tMna,struct('nSwitch',model.nSwitches, ...
    'eventTimes',tMna(2),'states',[1 0]));
simOff = otr_simulate_circuit(model,tMna,0,scheduleOff, ...
    struct('initialState',eventOn.statePlus));
eventOff = simOff.eventRecords(1);
voltageJumpOff = norm(eventOff.statePlus(model.index.voltage)- ...
    eventOff.stateMinus(model.index.voltage),inf);

% A short driven two-cell slab exercises continuous integration, both
% event directions and the independent physical energy audit.
energyModel = otr_build_mna(struct('physicsMode','ideal-capacitance', ...
    'nCells',2,'includeParasitics',false,'Rseries',0.05,'Gshunt',0));
tEnergy = 0:0.05e-9:20e-9;
sourceEnergy = sin(2*pi*50e6*tEnergy).*exp(-0.5*((tEnergy-4e-9)/1.5e-9).^2);
scheduleEnergy = otr_switch_schedule(tEnergy,struct( ...
    'nSwitch',energyModel.nSwitches,'eventTimes',[8 13]*1e-9, ...
    'states',[0 1 0]));
simEnergy = otr_simulate_circuit(energyModel,tEnergy,sourceEnergy,scheduleEnergy);
energy = otr_circuit_energy(energyModel,simEnergy);
eventRelativeResidual = max([simEnergy.eventRecords.relativeResidual]);
assert(eventOn.chargeResidual < 1e-11 && lineCurrentJumpOn < 1e-13, ...
    'otr:validate:MnaOn','MNA ON event violates charge/current continuity.');
assert(voltageJumpOff < 1e-13 && eventOff.voltageContinuityResidual < 1e-13, ...
    'otr:validate:MnaOff','MNA OFF event violates voltage continuity.');
assert(all(isfinite(simEnergy.state(:))) && numel(simEnergy.eventRecords)==2, ...
    'otr:validate:MnaSmoke','MNA slab simulation produced invalid state/events.');
assert(eventRelativeResidual < 5e-10,'otr:validate:MnaBoundaryResidual', ...
    'MNA event boundary residual %.3g is too large.',eventRelativeResidual);
assert(energy.relativeBalanceResidual < 5e-8,'otr:validate:MnaEnergy', ...
    'MNA relative energy-balance residual %.3g is too large.', ...
    energy.relativeBalanceResidual);
report.mna = struct('onChargeResidual',eventOn.chargeResidual, ...
    'onLineCurrentJump',lineCurrentJumpOn,'offVoltageJump',voltageJumpOff, ...
    'maxEventRelativeResidual',eventRelativeResidual, ...
    'relativeEnergyBalanceResidual',energy.relativeBalanceResidual, ...
    'passed',true);

%% Save machine-readable report and an audit-friendly plain-text summary
report.elapsedSeconds = toc(started);
report.status = 'passed';
report.allPassed = true;
report.outputFiles = {fullfile(outputDir,'validation_report.mat'), ...
    fullfile(outputDir,'validation_summary.txt')};
save(report.outputFiles{1},'report');
localWriteSummary(report,report.outputFiles{2});
localPrintTable(report);
end

function localWriteSummary(report,filename)
fid = fopen(filename,'wt');
assert(fid >= 0,'otr:validate:SummaryOpen', ...
    'Could not open validation summary for writing: %s',filename);
cleaner = onCleanup(@() fclose(fid));
fprintf(fid,'Observation of temporal reflection - validation summary\n');
fprintf(fid,'Status: %s\n',upper(report.status));
fprintf(fid,'Timestamp: %s\n',char(report.timestamp));
fprintf(fid,'MATLAB: %s\n',report.matlabVersion);
fprintf(fid,'Elapsed: %.3f s\n\n',report.elapsedSeconds);
fprintf(fid,'S1 element max error: %.6g\n',report.s1.elementMaxAbsError);
fprintf(fid,'S1 determinant error: %.6g\n',report.s1.determinantError);
fprintf(fid,'S2 trace max error: %.6g\n',report.s2s3.traceMaxAbsError);
fprintf(fid,'S3 ZB_on(50 MHz): %.9g ohm\n',report.s2s3.ZBon50Ohm);
fprintf(fid,'Ideal map [MHz]: %.6f %.6f %.6f\n',report.frequencyMap.idealOutputMHz);
fprintf(fid,'Realistic map [MHz]: %.6f %.6f %.6f\n', ...
    report.frequencyMap.realisticOutputMHz);
fprintf(fid,'Map roundtrip max [Hz]: ideal %.6g; realistic %.6g\n', ...
    report.frequencyMap.idealRoundtripMaxHz, ...
    report.frequencyMap.realisticRoundtripMaxHz);
fprintf(fid,'Temporal interface [Ton Ron Toff Roff]: %.9g %.9g %.9g %.9g\n', ...
    report.temporalInterface.Ton,report.temporalInterface.Ron, ...
    report.temporalInterface.Toff,report.temporalInterface.Roff);
fprintf(fid,'Slab first zero [MHz]: theory %.6f; numeric %.6f\n', ...
    report.temporalSlab.firstZeroTheoryMHz,report.temporalSlab.firstZeroNumericMHz);
fprintf(fid,'FFT peaks [MHz]: real %.6f; complex %.6f\n', ...
    report.fft.realPeakMHz,report.fft.complexPeakMHz);
fprintf(fid,'Source data: directory %d; zip %d; checked files %d\n', ...
    report.sourceData.dataDirectoryPresent,report.sourceData.zipPresent, ...
    numel(report.sourceData.checkedFiles));
fprintf(fid,'MNA energy relative residual: %.6g\n', ...
    report.mna.relativeEnergyBalanceResidual);
fprintf(fid,'ALL CHECKS PASSED\n');
end

function localPrintTable(report)
fprintf('\nOTR automated validation: PASS\n');
fprintf('%-24s  %s\n','Check','Key result');
fprintf('%-24s  %s\n',repmat('-',1,24),repmat('-',1,38));
fprintf('%-24s  S1 %.2e; det %.2e\n','ABCD / S1', ...
    report.s1.elementMaxAbsError,report.s1.determinantError);
fprintf('%-24s  ZB_on(50 MHz) %.4f ohm\n','Bloch / S2-S3', ...
    report.s2s3.ZBon50Ohm);
fprintf('%-24s  [%.4f %.4f %.4f] MHz\n','fixed-beta ideal', ...
    report.frequencyMap.idealOutputMHz);
fprintf('%-24s  [%.4f %.4f %.4f] MHz\n','fixed-beta realistic', ...
    report.frequencyMap.realisticOutputMHz);
fprintf('%-24s  [%.3g %.3g %.3g %.3g]\n','S14-S17 T/R', ...
    report.temporalInterface.Ton,report.temporalInterface.Ron, ...
    report.temporalInterface.Toff,report.temporalInterface.Roff);
fprintf('%-24s  first zero %.4f MHz\n','temporal slab', ...
    report.temporalSlab.firstZeroNumericMHz);
fprintf('%-24s  complex peak %.1f MHz\n','FFT negative frequency', ...
    report.fft.complexPeakMHz);
fprintf('%-24s  %d files checked\n','official source data', ...
    numel(report.sourceData.checkedFiles));
fprintf('%-24s  energy residual %.2e\n','MNA smoke', ...
    report.mna.relativeEnergyBalanceResidual);
fprintf('Saved: %s\n\n',report.outputFiles{1});
end
