function summary = validate_v31_suite(options)
%VALIDATE_V31_SUITE  V3.1 根目录、传输线与可选论文复现总回归。
%
% summary = validate_v31_suite()
% summary = validate_v31_suite(struct('runPaperSmoke',true))
%
% 默认执行解析基准、FDTD 时间界面/终点记录、实验式多探针 FFT、模板
% 路径恢复、传输线完整回归和全仓库 Code Analyzer。论文复现冒烟会运行
% 多次有限空间 FDTD，耗时更长，需显式设置 runPaperSmoke=true。

if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('options 必须是标量结构体。');
end
runTransmission = read_logical(options,'runTransmission',true);
runPaperSmoke = read_logical(options,'runPaperSmoke',false);
showFigures = read_logical(options,'showFigures',false);

rootDirectory = fileparts(mfilename('fullpath'));
originalDirectory = pwd;
originalPath = path;
originalVisibility = get(groot,'defaultFigureVisible');
directoryCleanup = onCleanup(@() cd(originalDirectory));
pathCleanup = onCleanup(@() path(originalPath));
figureCleanup = onCleanup(@() set(groot, ...
    'defaultFigureVisible',originalVisibility));
cd(rootDirectory);
if ~showFigures
    set(groot,'defaultFigureVisible','off');
end

testNames = {'version and model contract', ...
    'Maxwell PWE/TMM analytic uniform medium', ...
    'Maxwell D/B FDTD interfaces and records', ...
    'multi-probe physical FFT and Floquet folding', ...
    'paper-template path restoration', ...
    'transmission-line validation', ...
    'optional paper reproduction smoke', ...
    'repository Code Analyzer'};
passed = false(size(testNames));

fprintf('V3.1 validation started with MATLAB %s.\n',version);

%% Version and public model contract
versionText = strtrim(fileread(fullfile(rootDirectory,'VERSION.txt')));
versionLines = regexp(versionText,'\r?\n','split');
assert(strcmp(versionLines{1},'3.1.0'), ...
    'VERSION.txt does not declare semantic version 3.1.0.');
transmissionDirectory = fullfile(rootDirectory,'Transmission line');
addpath(transmissionDirectory,'-begin');
model = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'Cpar',2e-12,'deltaC',0));
assert(strcmp(model.version,'3.1.0') && ...
    abs(model.functions.capacitanceBulk(0)-model.shunt.totalC0) <= ...
    64*eps(model.shunt.totalC0), ...
    'Transmission-line version or additive Cpar contract is invalid.');
passed(1) = true;
fprintf('  PASS  %s\n',testNames{1});

%% Uniform-medium Maxwell analytic baselines
epsilonUniform = 2.5;
k = [0.2 0.7 1.1];
fourier = pwe_fourier(@(time) epsilonUniform*ones(size(time)), ...
    struct('T',1,'Mtime',0,'Nt',16));
pwe = pwe_bands(fourier,k);
tmm = tmm_bands(k,[epsilonUniform epsilonUniform],1,[0.4 0.6]);
expected = [-k;k]/sqrt(epsilonUniform);
pweError = max(abs(sort(real(pwe.omega),1)-sort(expected,1)),[],'all');
tmmError = max(abs(sort(real(tmm.omega),1)-sort(expected,1)),[],'all');
assert(pweError < 1e-12 && tmmError < 1e-12 && ...
    max(abs(imag(pwe.omega)),[],'all') < 1e-12 && ...
    max(abs(imag(tmm.omega)),[],'all') < 1e-12, ...
    'Uniform-medium PWE/TMM analytic baseline failed.');
passed(2) = true;
fprintf('  PASS  %s (PWE %.3g, TMM %.3g)\n', ...
    testNames{2},pweError,tmmError);

%% D/B-Yee temporal continuity and non-divisible terminal record
x = 0:0.1:4;
dt = 0.05;
fdtdCfg = struct('x',x,'dt',dt,'nSteps',7, ...
    'epsFun',@(position,time) ones(size(position)), ...
    'E0',zeros(size(x)),'Hhalf0',zeros(1,numel(x)-1), ...
    'recordEvery',3,'recordField','E');
field = fdtd1d(fdtdCfg);
assert(field.recordSteps(end) == fdtdCfg.nSteps && ...
    abs(field.t(end)-fdtdCfg.nSteps*dt) <= 16*eps(field.t(end)), ...
    'fdtd1d omitted the requested final state.');

interfaceCfg = struct('x',x,'dt',dt,'nSteps',4, ...
    'epsFun',@(position,time) ...
    (1+double(time >= 2*dt))*ones(size(position)), ...
    'E0',ones(size(x)),'Hhalf0',zeros(1,numel(x)-1), ...
    'recordEvery',1,'recordField','D', ...
    'temporalInterfaces',2*dt);
interfaceField = fdtd1d(interfaceCfg);
assert(max(abs(interfaceField.D-1),[],'all') < 1e-12, ...
    'D was not continuous across a spatially uniform time interface.');

scanCfg = struct('x',x,'dt',dt,'nSteps',1, ...
    'epsFun',@(position,time) ones(size(position)), ...
    'muFun',@(position,time) ones(size(position)), ...
    'kScan',0,'xCenter',2,'pulseIntensityFwhm',0.8, ...
    'fieldAmplitude',1,'initialEpsilon',1,'muRelative',1, ...
    'probeIndices',[19 21 23],'zeroKPropagationDirection',-1, ...
    'certifiedMinimumEpsilon',1,'certifiedMinimumMu',1);
zeroScan = fdtd_gaussian_k_scan(scanCfg);
assert(zeroScan.propagationDirections == -1 && ...
    zeroScan.carrierGroupSpeedYee < 0, ...
    'Maxwell k_c=0 packet did not retain the requested direction.');
passed(3) = true;
fprintf('  PASS  %s\n',testNames{3});

%% Endpoint-free physical FFT, multi-probe sum, and explicit folding
T = 1;
periodCount = 7;
samplesPerPeriod = 5;
time = (0:periodCount*samplesPerPeriod).'/samplesPerPeriod;
Omega = 2*pi/T;
physicalTone = (1+2/periodCount)*Omega;
carrier = exp(-1i*physicalTone*time);
signals = [carrier,(0.4+0.2i)*carrier];
fftResult = fdtd_fft_bands(signals,time,0,struct( ...
    'temporalPeriod',T,'analysisTimeRange',[0 periodCount*T], ...
    'zeroPaddingFactor',1));
fftResultPadded = fdtd_fft_bands(signals,time,0,struct( ...
    'temporalPeriod',T,'analysisTimeRange',[0 periodCount*T], ...
    'zeroPaddingFactor',4));
[~,foldedPeak] = max(fftResult.foldedPower,[],1);
[~,rawPeak] = max(fftResult.rawPower,[],1);
rawArea = sum(fftResult.rawPower,1)* ...
    (fftResult.rawOmegaNormalized(2)-fftResult.rawOmegaNormalized(1));
paddedRawArea = sum(fftResultPadded.rawPower,1)* ...
    (fftResultPadded.rawOmegaNormalized(2)- ...
    fftResultPadded.rawOmegaNormalized(1));
assert(fftResult.probeCount == 2 && ...
    abs(fftResult.omegaNormalized(foldedPeak)-2/periodCount) < 1e-12 && ...
    abs(fftResult.rawOmegaNormalized(rawPeak)- ...
    (1+2/periodCount)) < 1e-12 && ...
    abs(fftResult.rawColumnPower- ...
    fftResultPadded.rawColumnPower) <= ...
    1e-12*fftResult.rawColumnPower && ...
    abs(rawArea-paddedRawArea) <= 1e-12*rawArea && ...
    isfield(fftResult,'columnNormalizedPower') && ...
    isfield(fftResult,'spectralNormalization') && ...
    isequal(fftResult.analysisRows,1:periodCount*samplesPerPeriod), ...
    'Physical FFT/folding or single-k multi-probe handling failed.');
passed(4) = true;
fprintf('  PASS  %s\n',testNames{4});

%% Root-template resolution must leave the caller path byte-for-byte intact
topologyDirectory = fullfile(rootDirectory,'topology_aspect');
addpath(topologyDirectory,'-begin');
pathBeforeTemplateCheck = path;
[templateSource,templateCleanup] = use_root_templates( ...
    {'fdtd1d','fdtd_fft_bands'}); %#ok<ASGLU>
assert(all(startsWith(templateSource.resolvedFiles,rootDirectory)), ...
    'A topology reproduction resolved a non-root numerical template.');
clear templateCleanup;
assert(strcmp(path,pathBeforeTemplateCheck), ...
    'use_root_templates did not exactly restore the caller path order.');
passed(5) = true;
fprintf('  PASS  %s\n',testNames{5});

%% Full transmission-line suite
if runTransmission
    oldDirectory = pwd;
    cd(transmissionDirectory);
    transmission = validate_tl_suite();
    cd(oldDirectory);
    assert(transmission.allPassed,'Transmission-line validation failed.');
    fprintf('  PASS  %s\n',testNames{6});
else
    transmission = struct('status','skipped by options.runTransmission');
    fprintf('  SKIP  %s\n',testNames{6});
end
passed(6) = true;

%% Optional finite-sample paper-reproduction smoke tests
if runPaperSmoke
    fullMomentumDirectory = fullfile(rootDirectory,'Full_momemtum');
    addpath(fullMomentumDirectory,'-begin');
    fullMomentum = reproduce_figures_2_3(struct( ...
        'quick',true,'runFields',false,'runPhaseMap',false, ...
        'runFftBands',true,'saveOutputs',false));
    fullErrors = [fullMomentum.figure2.fdtdFft.cases.validation];
    fullMaximum = max([fullErrors.maximumDominantErrorOverOmega, ...
        fullMomentum.figure3.fdtdFft.case.validation. ...
        maximumDominantErrorOverOmega]);
    assert(isfinite(fullMaximum) && fullMaximum <= 2/6, ...
        'Full_momemtum quick FDTD-FFT peak error exceeds two native bins.');
    assert(isfield(fullMomentum.figure2.fdtdFft.cases(1).bands, ...
        'spectralNormalization'), ...
        'Full_momemtum omitted the shared FFT normalization metadata.');

    topology = reproduce_fdtd_band(struct('nK',11, ...
        'analysisPeriodCount',6,'stepsPerPeriod',100, ...
        'zeroPaddingFactor',2));
    assert(topology.validation.stableStrongSampleCount > 0 && ...
        all(isfinite(topology.foldedPower),'all') && ...
        isfield(topology.samplingMetadata,'spectralNormalization'), ...
        'topology_aspect finite-sample FFT smoke test failed.');
    fprintf('  PASS  %s\n',testNames{7});
else
    fullMomentum = struct('status','skipped by options.runPaperSmoke');
    topology = struct('status','skipped by options.runPaperSmoke');
    fprintf('  SKIP  %s\n',testNames{7});
end
passed(7) = true;

%% Whole-repository Code Analyzer
mFiles = dir(fullfile(rootDirectory,'**','*.m'));
analyzerIssues = repmat(struct('file','','line',0,'id','','message',''),0,1);
for fileIndex = 1:numel(mFiles)
    filePath = fullfile(mFiles(fileIndex).folder,mFiles(fileIndex).name);
    issues = checkcode(filePath,'-id');
    for issueIndex = 1:numel(issues)
        analyzerIssues(end+1) = struct( ...
            'file',filePath,'line',issues(issueIndex).line, ...
            'id',issues(issueIndex).id, ...
            'message',issues(issueIndex).message); %#ok<AGROW>
    end
end
assert(isempty(analyzerIssues), ...
    'Code Analyzer reported %d issue(s).',numel(analyzerIssues));
passed(8) = true;
fprintf('  PASS  %s (%d MATLAB files)\n',testNames{8},numel(mFiles));

executed = [true true true true true runTransmission runPaperSmoke true];
summary = struct('packageVersion','3.1.0','matlabVersion',version, ...
    'rootDirectory',rootDirectory,'testNames',{testNames}, ...
    'executed',executed,'skipped',~executed, ...
    'passed',passed,'allPassed',all(passed(executed)), ...
    'uniformPweError',pweError,'uniformTmmError',tmmError, ...
    'transmission',transmission,'fullMomentum',fullMomentum, ...
    'topologyAspect',topology,'analyzerIssues',analyzerIssues, ...
    'options',options);
fprintf(['V3.1 validation passed: %d/%d executed checks; ' ...
    '%d optional checks skipped.\n'], ...
    sum(passed & executed),sum(executed),sum(~executed));

if ~showFigures
    close all;
end
clear figureCleanup pathCleanup directoryCleanup;
end

% -------------------------------------------------------------------------
function value = read_logical(options,name,defaultValue)
if isfield(options,name) && ~isempty(options.(name))
    value = options.(name);
else
    value = defaultValue;
end
if ~islogical(value) || ~isscalar(value)
    error('options.%s 必须是逻辑标量。',name);
end
end
