function summary = validate_tl_suite()
%VALIDATE_TL_SUITE Regression tests for the transmission-line module.
% Run from this directory with MATLAB R2020a+ and Base MATLAB only.

fprintf('Transmission-line validation started with MATLAB %s.\n',version);
moduleDirectory = fileparts(mfilename('fullpath'));
originalDirectory = pwd;
cleanupDirectory = onCleanup(@() cd(originalDirectory));
cd(moduleDirectory);
assert(startsWith(which('tl_build_model'),moduleDirectory), ...
    'tl_build_model does not resolve to this module directory.');

testNames = { ...
    'paper anchors and assumptions', ...
    'static analytic dispersion and TMM', ...
    'PWE versus time TMM', ...
    'passive loss sign', ...
    'finite-chain FDTD energy and Q continuity', ...
    'CROW finite-chain smoke test', ...
    'synthetic signed x-t FFT', ...
    'synthetic fixed-probe FFT and Floquet folding', ...
    'finite-chain Gaussian k scan', ...
    'Bloch FFT versus TMM', ...
    'fit and component interfaces', ...
    'CROW complete Floquet spectrum', ...
    'square-wave phase periodicity', ...
    'CROW loss ledger and driven-port termination', ...
    'finite-Cblock anchors and component tolerances', ...
    'finite-chain versus bulk dynamic evolution', ...
    'short-boundary probe selection', ...
    'Code Analyzer'};
passed = false(size(testNames));

%% Paper anchors and explicit assumptions
sspp = tl_build_model(struct('topology','sspp','allowAssumptions',true));
assert(strcmp(sspp.version,'3.1.0'),'Transmission-line model version is stale.');
expectedLeffective = 4/((2*pi*371e6)^2*19.8e-12);
assert_relative(sspp.derived.effectiveBoundaryInductance, ...
    expectedLeffective,1e-12,'SSPP paper anchor');
crow = tl_build_model(struct('topology','crow','allowAssumptions',true));
assert_relative(crow.derived.fcolHz,314.7e6,2e-3,'CROW fcol anchor');
assumptionRejected = false;
try
    tl_build_model(struct('topology','sspp'));
catch
    assumptionRejected = true;
end
assert(assumptionRejected,'Missing paper parameters were silently assumed.');
parasiticModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'deltaC',0,'Cpar',2e-12));
assert_relative(parasiticModel.functions.capacitanceBulk(0), ...
    parasiticModel.shunt.C0+parasiticModel.shunt.Cpar,1e-14, ...
    'additive Cpar activation');
passed(1) = true;
fprintf('  PASS  %s\n',testNames{1});

%% Constant-coefficient SSPP analytic dispersion and exact monodromy
staticCfg = struct('topology','sspp','allowAssumptions',true, ...
    'a',5e-3,'Ls',45e-9,'mutualS',3e-9,'C0',20e-12, ...
    'deltaC',0,'Rs',0,'Gp',0,'fmHz',600e6);
staticModel = tl_build_model(staticCfg);
kStatic = [0.13 0.37 0.71]*pi/staticModel.cell.a;
Lk = staticModel.series.Ls+2*staticModel.series.mutualS* ...
    cos(kStatic*staticModel.cell.a);
omegaAnalytic = 2*abs(sin(kStatic*staticModel.cell.a/2))./ ...
    sqrt(Lk*staticModel.shunt.totalC0);
tmmStatic = tl_tmm_bands(staticModel,kStatic,struct('temporalSlices',32));
expected = [-omegaAnalytic;omegaAnalytic];
expected = fold_frequency(expected,staticModel.modulation.OmegaRadPerSec);
staticError = spectral_set_error(tmmStatic.omegaFolded,expected, ...
    staticModel.modulation.OmegaRadPerSec);
assert(staticError < 1e-11,'Static TMM error %.3g exceeds 1e-11.',staticError);
passed(2) = true;
fprintf('  PASS  %s (error %.3g)\n',testNames{2},staticError);

%% Modulated PWE/TMM cross-check
dynamicModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true));
kDynamic = [0.17 0.39 0.63 0.84]*pi/dynamicModel.cell.a;
fourier = tl_pwe_fourier(dynamicModel,struct('Mtime',5,'Nt',256));
pwe = tl_pwe_bands(fourier,dynamicModel,kDynamic,struct());
mismatchRejected = false;
try
    mismatchedModel = tl_build_model(struct('topology','sspp', ...
        'allowAssumptions',true,'Cpar',1e-13));
    tl_pwe_bands(fourier,mismatchedModel,kDynamic,struct());
catch
    mismatchRejected = true;
end
assert(mismatchRejected,'PWE accepted Fourier data from another model.');
tmm = tl_tmm_bands(dynamicModel,kDynamic,struct('temporalSlices',1024));
pweTmmError = spectral_set_error(pwe.omegaSelected,tmm.omegaFolded, ...
    dynamicModel.modulation.OmegaRadPerSec);
assert(pweTmmError < 0.01, ...
    'PWE/TMM circular spectral error %.3g exceeds 0.01.',pweTmmError);
passed(3) = true;
fprintf('  PASS  %s (error/Omega %.3g)\n',testNames{3},pweTmmError);

%% Passive loss sign under exp(i*k*x-i*omega*t)
lossModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'deltaC',0,'Rs',0.4,'Gp',2e-4));
lossBands = tl_tmm_bands(lossModel,kDynamic,struct('temporalSlices',64));
passiveMaximum = max(imag(lossBands.omegaFolded),[],'all')/ ...
    lossModel.derived.omegaMaximumEstimate;
assert(passiveMaximum <= 1e-11, ...
    'A passive model has positive Im(omega): %.3g.',passiveMaximum);
passed(4) = true;
fprintf('  PASS  %s\n',testNames{4});

%% Finite chain energy and time-interface charge continuity
finiteModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',16,'deltaC',0));
nodeNumber = (0:finiteModel.finite.cellCount-1).';
initialVoltage = exp(1i*2*pi*nodeNumber/finiteModel.finite.cellCount);
fdtdCfg = struct('dt',0.05/finiteModel.derived.omegaMaximumEstimate, ...
    'nSteps',500,'recordEvery',5,'boundaryType','periodic', ...
    'modulationEnabled',false,'V0',initialVoltage);
field = tl_fdtd1d(finiteModel,fdtdCfg);
energyDrift = (max(field.energy.total)-min(field.energy.total))/ ...
    mean(field.energy.total);
assert(energyDrift < 1e-3,'FDTD energy drift %.3g exceeds 0.1%%.',energyDrift);
terminalCfg = fdtdCfg;
terminalCfg.nSteps = 17;
terminalCfg.recordEvery = 5;
terminalField = tl_fdtd1d(finiteModel,terminalCfg);
assert(terminalField.grid.recordSteps(end) == terminalCfg.nSteps, ...
    'FDTD omitted a non-divisible terminal record.');
cachedCfg = terminalCfg;
cachedCfg.stabilityAudit = terminalField.grid.stabilityAudit;
cachedField = tl_fdtd1d(finiteModel,cachedCfg);
assert(strcmp(cachedField.grid.stabilityAuditSource,'validated-reuse') && ...
    isequal(terminalField.node.V,cachedField.node.V), ...
    'Validated stability-audit reuse changed the finite-chain solution.');

interfaceModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',8));
stepsPerPeriod = 64;
interfaceCfg = struct('dt',interfaceModel.modulation.period/stepsPerPeriod, ...
    'nSteps',stepsPerPeriod+2,'recordEvery',1,'boundaryType','periodic', ...
    'modulationEnabled',true, ...
    'modulationStart',interfaceModel.modulation.period,'V0',ones(8,1));
interfaceField = tl_fdtd1d(interfaceModel,interfaceCfg);
qBefore = interfaceField.node.Q(stepsPerPeriod,:);
qAt = interfaceField.node.Q(stepsPerPeriod+1,:);
chargeJump = norm(double(qAt-qBefore))/max(norm(double(qBefore)),realmin);
assert(chargeJump < 1e-12, ...
    'Charge changed across a uniform capacitance time interface.');
passed(5) = true;
fprintf('  PASS  %s (energy drift %.3g)\n',testNames{5},energyDrift);

%% CROW finite-Cblock finite-chain path
crowFinite = tl_build_model(struct('topology','crow', ...
    'allowAssumptions',true,'cellCount',8));
crowCfg = struct('dt',0.04/crowFinite.derived.omegaMaximumEstimate, ...
    'nSteps',40,'recordEvery',4,'boundaryType','matched', ...
    'modulationEnabled',false,'V0',[1;zeros(7,1)]);
crowField = tl_fdtd1d(crowFinite,crowCfg);
assert(isfield(crowField.resonator,'Qblock') && ...
    all(isfinite(crowField.resonator.Qblock),'all'), ...
    'CROW finite-Cblock state was not returned correctly.');
passed(6) = true;
fprintf('  PASS  %s\n',testNames{6});

%% Synthetic x-t transform at exact signed bins
a = 4e-3;
T = 1e-6;
nTime = 128;
nCell = 16;
dt = T/16;
time = (0:nTime-1).'*dt;
cells = 0:nCell-1;
x = cells*a;
Omega = 2*pi/T;
kExpected = 3*2*pi/(nCell*a);
omegaExpected = 0.25*Omega;
data = exp(-1i*omegaExpected*time)*exp(1i*kExpected*x);
observation = struct('data',data,'x',x,'t',time, ...
    'cellIndex',cells,'channelId',ones(1,nCell), ...
    'channelOffset',zeros(1,nCell),'observableName','synthetic I');
fft = tl_xt_fft_bands(observation,observation,struct( ...
    'cellPeriod',a,'temporalPeriod',T,'zeroPaddingTime',2, ...
    'zeroPaddingSpace',2,'referenceThresholdDb',80,'ridgeCount',1));
fftNoPadding = tl_xt_fft_bands(observation,observation,struct( ...
    'cellPeriod',a,'temporalPeriod',T,'zeroPaddingTime',1, ...
    'zeroPaddingSpace',1,'referenceThresholdDb',80,'ridgeCount',1));
[~,peakLinear] = max(fft.foldedPower,[],'all','linear');
[peakOmegaIndex,peakKIndex] = ind2sub(size(fft.foldedPower),peakLinear);
assert(abs(fft.k(peakKIndex)-kExpected) < 1e-12*abs(kExpected));
assert(abs(fft.foldedOmega(peakOmegaIndex)-omegaExpected) < ...
    1e-12*abs(omegaExpected));
assert_relative(max(fft.foldedPower,[],'all'), ...
    max(fftNoPadding.foldedPower,[],'all'),1e-12, ...
    'x-t zero-padding-invariant coherent power');
highOmega = 3.25*Omega;
mixedObservation = observation;
mixedObservation.data = data+5*exp(-1i*highOmega*time)* ...
    exp(1i*kExpected*x);
fullFold = tl_xt_fft_bands(mixedObservation,mixedObservation,struct( ...
    'cellPeriod',a,'temporalPeriod',T,'zeroPaddingTime',2, ...
    'zeroPaddingSpace',2,'referenceThresholdDb',80,'ridgeCount',1));
limitedFold = tl_xt_fft_bands(mixedObservation,mixedObservation,struct( ...
    'cellPeriod',a,'temporalPeriod',T,'zeroPaddingTime',2, ...
    'zeroPaddingSpace',2,'referenceThresholdDb',80,'ridgeCount',1, ...
    'maximumPhysicalOmega',Omega));
assert(max(limitedFold.foldedPower,[],'all') < ...
    0.2*max(fullFold.foldedPower,[],'all') && ...
    any(~limitedFold.foldingPhysicalFrequencyMask), ...
    'maximumPhysicalOmega did not limit Floquet-folding input bins.');
passed(7) = true;
fprintf('  PASS  %s\n',testNames{7});

%% Synthetic multi-probe time FFT with odd sampling and explicit folding
probeT = 1e-6;
probeOmega = 2*pi/probeT;
probeDt = probeT/5;
probePeriods = 7;
probeTime = (0:probePeriods*5).'*probeDt;
probeK = [0.2 0.6];
probeTone = (1+2/probePeriods)*probeOmega;
probeData = complex(zeros(numel(probeTime),2,numel(probeK)));
for index = 1:numel(probeK)
    carrier = exp(-1i*probeTone*probeTime);
    probeData(:,1,index) = carrier;
    probeData(:,2,index) = (0.4+0.2i)*carrier;
end
probeFft = tl_fdtd_fft_bands(probeData,probeTime,probeK,struct( ...
    'temporalPeriod',probeT,'analysisTimeRange',[0 probePeriods*probeT], ...
    'zeroPaddingFactor',1,'returnProbePower',true));
probeFftPadded = tl_fdtd_fft_bands(probeData,probeTime,probeK,struct( ...
    'temporalPeriod',probeT, ...
    'analysisTimeRange',[0 probePeriods*probeT], ...
    'zeroPaddingFactor',4));
[~,probePeak] = max(probeFft.foldedPower,[],1);
assert(all(abs(probeFft.omegaOverOmega(probePeak)-2/probePeriods) < 1e-12));
[~,probeRawPeak] = max(probeFft.rawPower,[],1);
assert(all(abs(probeFft.rawOmegaOverOmega(probeRawPeak)- ...
    (1+2/probePeriods)) < 1e-12), ...
    'The full physical-frequency spectrum was not retained correctly.');
assert(probeFft.probeCount == 2 && ...
    size(probeFft.rawProbePower,2) == 2, ...
    'Fixed-probe power was not retained per probe.');
assert_relative(sum(probeFft.foldedProbePower,'all'), ...
    sum(probeFft.rawProbePower,'all'),1e-12,'Floquet folding total power');
assert(norm(reshape(sum(probeFft.foldedProbePower,2), ...
    size(probeFft.foldedPower))-probeFft.foldedPower,'fro') < ...
    1e-12*norm(probeFft.foldedPower,'fro'), ...
    'Folded probe powers do not sum to the returned total.');
assert(max(abs(probeFft.rawColumnPower- ...
    probeFftPadded.rawColumnPower)) <= ...
    1e-12*max(probeFft.rawColumnPower) && ...
    isfield(probeFft,'spectralNormalization'), ...
    'Fixed-probe raw power changes under zero padding.');
singleKProbeFft = tl_fdtd_fft_bands(probeData(:,:,1),probeTime,probeK(1), ...
    struct('temporalPeriod',probeT, ...
    'analysisTimeRange',[0 probePeriods*probeT]));
assert(singleKProbeFft.probeCount == 2, ...
    'A single-k multi-probe matrix was misread as multiple k columns.');
passed(8) = true;
fprintf('  PASS  %s\n',testNames{8});

%% Finite-chain Gaussian packets use complete-space FDTD probe data
packetModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',128,'deltaC',0, ...
    'fmHz',600e6));
packetT = packetModel.modulation.period;
packetK = [0 0.25 0.5 0.75]*pi/packetModel.cell.a;
packetScanCfg = struct('kScan',packetK,'dt',packetT/64, ...
    'nSteps',8*64,'recordEvery',1,'pulseIntensityFwhmCells',14, ...
    'voltageAmplitude',1,'centerNode',64, ...
    'probeNodeIndices',[59 62 64 66 69], ...
    'boundaryType','open','modulationEnabled',false, ...
    'initialTailTolerance',1e-4,'requireNoBoundaryArrival',true, ...
    'progressEvery',10);
packetScan = tl_fdtd_gaussian_k_scan(packetModel,packetScanCfg);
packetFft = tl_fdtd_fft_bands(packetScan.probeSignals, ...
    packetScan.time,packetK,struct('temporalPeriod',packetT, ...
    'analysisTimeRange',[0 8*packetT],'zeroPaddingFactor',2));
packetTmm = tl_tmm_bands(packetModel,packetK,struct('temporalSlices',32));
[~,packetPeak] = max(packetFft.foldedPower,[],1);
packetError = 0;
for index = 1:numel(packetK)
    distance = circular_distance(packetFft.foldedOmega(packetPeak(index)), ...
        real(packetTmm.omegaFolded(:,index)), ...
        packetModel.modulation.OmegaRadPerSec);
    packetError = max(packetError,min(distance)/ ...
        packetModel.modulation.OmegaRadPerSec);
end
assert(packetError <= 2*packetFft.nativeOmegaResolutionNormalized, ...
    'Finite-chain Gaussian FFT ridge exceeds two native frequency bins.');
assert(packetScan.initialEdgeAmplitudeBound < ...
    packetScan.initialTailTolerance, ...
    'Finite-chain Gaussian source does not satisfy its tail audit.');
assert(packetScan.initialModeReferenceK(1) > 0 && ...
    packetScan.carrierGroupVelocity(1) > 0 && ...
    packetScan.initialDirectionalPower(1) > 0 && ...
    packetScan.initialFiniteCapacitanceUniform && ...
    max(packetScan.initialVoltageEnvelopeRelativeError) < 1e-14 && ...
    strcmp(packetScan.representativeField.grid.stabilityAuditSource, ...
    'validated-reuse') && ...
    norm(packetScan.representativeField.grid.stabilityAudit.omegaMaximum- ...
    packetScan.stabilityAudit.omegaMaximum) == 0, ...
    'The k_c=0 acoustic packet or shared stability audit is inconsistent.');

nonuniformModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',64, ...
    'phaseByCell',linspace(0,pi/2,64)));
nonuniformCfg = struct('kScan',0.2*pi/nonuniformModel.cell.a, ...
    'dt',0.05/nonuniformModel.derived.omegaMaximumEstimate, ...
    'nSteps',2,'recordEvery',1,'pulseIntensityFwhmCells',8, ...
    'voltageAmplitude',1,'centerNode',32, ...
    'probeNodeIndices',[30 32 34],'boundaryType','open', ...
    'modulationEnabled',true,'initialTailTolerance',1e-4, ...
    'requireNoBoundaryArrival',false,'progressEvery',10);
warningState = warning('query', ...
    'tl_fdtd_gaussian_k_scan:NonuniformInitialCapacitance');
warning('off','tl_fdtd_gaussian_k_scan:NonuniformInitialCapacitance');
nonuniformScan = tl_fdtd_gaussian_k_scan( ...
    nonuniformModel,nonuniformCfg);
warning(warningState);
assert(~nonuniformScan.initialFiniteCapacitanceUniform && ...
    max(nonuniformScan.initialVoltageEnvelopeRelativeError) < 1e-14, ...
    'A spatially nonuniform initial capacitance distorted the V Gaussian.');
passed(9) = true;
fprintf('  PASS  %s (error/Omega %.3g)\n',testNames{9},packetError);

%% Stroboscopic bulk FFT peak against a TMM eigenfrequency set
kBloch = [0.23 0.51 0.79]*pi/dynamicModel.cell.a;
bloch = tl_bloch_fft_bands(dynamicModel,kBloch,struct( ...
    'stepsPerPeriod',256,'temporalCellCount',64, ...
    'zeroPaddingFactor',4));
tmmBloch = tl_tmm_bands(dynamicModel,kBloch, ...
    struct('temporalSlices',1024));
blochError = 0;
for index = 1:numel(kBloch)
    distance = circular_distance(bloch.ridgeOmega(index), ...
        real(tmmBloch.omegaFolded(:,index)), ...
        dynamicModel.modulation.OmegaRadPerSec);
    blochError = max(blochError,min(distance)/ ...
        dynamicModel.modulation.OmegaRadPerSec);
end
assert(blochError <= 2*bloch.nativeOmegaResolution/ ...
    dynamicModel.modulation.OmegaRadPerSec, ...
    'Bloch FFT ridge error exceeds two native frequency bins.');

exactOrder = 5;
exactSampleCount = 32;
exactOmega = exactOrder/exactSampleCount* ...
    staticModel.modulation.OmegaRadPerSec;
exactK = fzero(@(value) 2*abs(sin(value*staticModel.cell.a/2))/ ...
    sqrt((staticModel.series.Ls+2*staticModel.series.mutualS* ...
    cos(value*staticModel.cell.a))*staticModel.shunt.totalC0)- ...
    exactOmega,[0 pi/staticModel.cell.a]);
blochNative = tl_bloch_fft_bands(staticModel,exactK,struct( ...
    'stepsPerPeriod',8,'temporalCellCount',exactSampleCount, ...
    'zeroPaddingFactor',1));
blochPadded = tl_bloch_fft_bands(staticModel,exactK,struct( ...
    'stepsPerPeriod',8,'temporalCellCount',exactSampleCount, ...
    'zeroPaddingFactor',4));
assert_relative(max(blochNative.rawPower,[],'all'), ...
    max(blochPadded.rawPower,[],'all'),1e-11, ...
    'Bloch zero-padding-invariant coherent power');
assert(isfield(blochNative,'spectralNormalization'), ...
    'Bloch FFT omitted its spectral normalization metadata.');
passed(10) = true;
fprintf('  PASS  %s (error/Omega %.3g)\n',testNames{10},blochError);

%% Fit and selection interfaces on synthetic/target-only data
fitK = [0.3 0.6].'*pi/staticModel.cell.a;
fitFrequency = zeros(size(fitK));
for index = 1:numel(fitK)
    [Aconstant,AinverseC] = staticModel.functions.bulkMatrices(fitK(index));
    fitFrequency(index) = max(real(1i*eig(Aconstant+ ...
        AinverseC/staticModel.shunt.totalC0)))/(2*pi);
end
fitData = struct('staticDispersion',struct('kRadPerM',fitK, ...
    'frequencyHz',fitFrequency,'uncertaintyHz',1e4));
fitBase = staticCfg;
fitBase.Ls = 40e-9;
fitResult = tl_fit_parameters(fitBase,fitData,struct( ...
    'parameterNames',{{'Ls'}},'maxIterations',40,'maxEvaluations',100));
assert_relative(fitResult.parameterValues.Ls,staticCfg.Ls,1e-6, ...
    'synthetic Ls fit');
selection = tl_select_components(staticModel,struct(),struct());
assert(selection.monteCarlo.sampleCount >= 1000 && ...
    strcmp(selection.status,'simulation-seed component screening'));
passed(11) = true;
fprintf('  PASS  %s\n',testNames{11});

%% Both CROW circuit limits must retain every independent Floquet mode.
crowSpectralError = 0;
for blockCapacitance = [200e-12 Inf]
    spectralModel = tl_build_model(struct('topology','crow', ...
        'allowAssumptions',true,'Cblock',blockCapacitance));
    spectralK = [0 .2 .5 .8 1]*pi/spectralModel.cell.a;
    spectralPwe = tl_pwe_bands(tl_pwe_fourier(spectralModel, ...
        struct('Mtime',5,'Nt',256)),spectralModel,spectralK,struct());
    spectralTmm = tl_tmm_bands(spectralModel,spectralK, ...
        struct('temporalSlices',1024));
    crowSpectralError = max(crowSpectralError,spectral_set_error( ...
        spectralPwe.omegaSelected,spectralTmm.omegaFolded, ...
        spectralModel.modulation.OmegaRadPerSec));
end
assert(crowSpectralError < 1e-5, ...
    'CROW PWE omitted a mode or selected duplicate Floquet replicas.');
passed(12) = true;
fprintf('  PASS  %s (error/Omega %.3g)\n',testNames{12},crowSpectralError);

%% An arbitrary phase offset must not lose square-wave interfaces.
squareCfg = struct('topology','crow','allowAssumptions',true, ...
    'modulationType','square','dutyCycle',0.31,'modulationPhase',0.43);
squareModel = tl_build_model(squareCfg);
squareK = 0.37*pi/squareModel.cell.a;
squareBase = tl_tmm_bands(squareModel,squareK,struct());
for turns = [-19 23]
    squareCfg.modulationPhase = 0.43+turns*2*pi;
    shiftedModel = tl_build_model(squareCfg);
    shiftedTmm = tl_tmm_bands(shiftedModel,squareK,struct());
    shiftedFft = tl_bloch_fft_bands(shiftedModel,squareK, ...
        struct('temporalCellCount',8));
    assert(norm(shiftedTmm.U-squareBase.U,'fro')/ ...
        norm(squareBase.U,'fro') < 1e-11);
    assert(norm(shiftedFft.monodromy-shiftedTmm.U,'fro')/ ...
        norm(shiftedTmm.U,'fro') < 1e-12);
end
passed(13) = true;
fprintf('  PASS  %s\n',testNames{13});

%% Damped CROW energy balance converges with timestep; no double termination.
ledgerModel = tl_build_model(struct('topology','crow', ...
    'allowAssumptions',true,'cellCount',8,'deltaC',0,'R0',1.5));
ledgerResidual = zeros(1,2);
for refinement = 1:2
    ledgerCfg = struct('dt',ledgerModel.modulation.period/(64*refinement), ...
        'nSteps',8*64*refinement,'modulationEnabled',false, ...
        'boundaryType','periodic','V0',ones(8,1));
    ledgerField = tl_fdtd1d(ledgerModel,ledgerCfg);
    assert(ledgerField.energy.resonatorDissipation(end) > 0.5* ...
        ledgerField.energy.total(1));
    ledgerResidual(refinement) = max(abs(ledgerField.energy.ledgerResidual))/ ...
        ledgerField.energy.total(1);
end
assert(ledgerResidual(2) < 0.35*ledgerResidual(1) && ...
    ledgerResidual(2) < 1e-3,'CROW R0 energy balance did not converge.');
portModel = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',8,'deltaC',0, ...
    'Zsource',50,'Zload',50));
portCfg = struct('dt',portModel.modulation.period/128,'nSteps',256, ...
    'modulationEnabled',false,'boundaryType','matched', ...
    'source',struct('type','thevenin','node',1,'impedance',75, ...
    'waveformFcn',@(t) exp(-((t/portModel.modulation.period-0.5)/0.15).^2)));
leftPort = tl_fdtd1d(portModel,portCfg);
portCfg.source.node = 8;
rightPort = tl_fdtd1d(portModel,portCfg);
assert(norm(leftPort.node.V-fliplr(rightPort.node.V),'fro')/ ...
    norm(leftPort.node.V,'fro') < 1e-12,'Driven ports are not reciprocal.');
% Changing the unused termination at a driven port must not change its load.
changedPort = tl_build_model(struct('topology','sspp', ...
    'allowAssumptions',true,'cellCount',8,'deltaC',0, ...
    'Zsource',50,'Zload',123));
changedField = tl_fdtd1d(changedPort,portCfg);
assert(isequal(rightPort.node.V,changedField.node.V), ...
    'The driven port still includes a duplicate terminal conductance.');
passed(14) = true;
fprintf('  PASS  %s (ledger residual %.3g)\n',testNames{14},ledgerResidual(2));

%% Analytic roots, fit anchors and tolerance outputs use the same circuit.
anchorCfg = struct('topology','crow','allowAssumptions',true,'deltaC',0);
anchorModel = tl_build_model(anchorCfg);
for ka = [0 pi]
    [Ac,Ai] = anchorModel.functions.bulkMatrices(ka/anchorModel.cell.a);
    exact = max(real(1i*eig(Ac+Ai/anchorModel.shunt.totalC0)))/(2*pi);
    if ka == 0, expected = anchorModel.derived.staticCenterFrequencyHz;
    else, expected = anchorModel.derived.staticBoundaryFrequencyHz; end
    assert_relative(exact,expected,1e-12,'CROW analytic anchor');
end
anchorData = struct('anchors',struct( ...
    'fcolHz',anchorModel.derived.staticCenterFrequencyHz, ...
    'fcolUncertaintyHz',1e4, ...
    'boundaryFrequencyHz',anchorModel.derived.staticBoundaryFrequencyHz, ...
    'boundaryUncertaintyHz',1e4));
fitAnchorCfg = anchorCfg;
fitAnchorCfg.Cblock = 240e-12;
anchorFit = tl_fit_parameters(fitAnchorCfg,anchorData, ...
    struct('parameterNames',{{'Cblock'}},'maxIterations',100));
assert_relative(anchorFit.parameterValues.Cblock,200e-12,1e-5, ...
    'finite-Cblock anchor fit');
anchorSelection = tl_select_components(anchorModel,struct(),struct());
assert_relative(anchorSelection.monteCarlo.boundaryFrequencyHz(2), ...
    anchorModel.derived.staticBoundaryFrequencyHz,1e-12,'CROW tolerance edge');
assert_relative(anchorSelection.monteCarlo.fcolHz(2), ...
    anchorModel.derived.staticCenterFrequencyHz,1e-12,'CROW tolerance center');
passed(15) = true;
fprintf('  PASS  %s\n',testNames{15});

%% Non-paper parameters, mutual coupling and loss: finite chain versus bulk.
dynamicErrors = dynamic_circuit_errors();
assert(all(dynamicErrors(:,2) < 0.35*dynamicErrors(:,1)) && ...
    all(dynamicErrors(:,2) < 2e-4), ...
    'Finite-chain evolution does not converge to the same bulk circuit.');
passed(16) = true;
fprintf('  PASS  %s (maximum error %.3g)\n',testNames{16},max(dynamicErrors(:,2)));

%% Short boundaries support any number of interior probes, in any order.
shortCfg = packetScanCfg;
shortCfg.boundaryType = 'short';
shortCfg.kScan = packetK(2);
shortCfg.nSteps = 2;
for probes = {64,[62 64],[62 64 66],[59 62 64 66 69]}
    shortCfg.probeNodeIndices = probes{1};
    shortScan = tl_fdtd_gaussian_k_scan(packetModel,shortCfg);
    assert(size(shortScan.probeSignals,2) == numel(probes{1}) && ...
        all(isfinite(shortScan.probeSignals),'all'));
    assert(all(shortScan.representativeField.node.V(:,[1 end]) == 0,'all'));
end
for probes = {[128 64],[64 1],[64 66 128]}
    shortCfg.probeNodeIndices = probes{1};
    rejected = false;
    try
        tl_fdtd_gaussian_k_scan(packetModel,shortCfg);
    catch exception
        rejected = contains(exception.message,'short-circuited terminal');
    end
    assert(rejected,'A voltage probe at a shorted endpoint was accepted.');
end
passed(17) = true;
fprintf('  PASS  %s\n',testNames{17});

%% Code Analyzer (include shared private helpers).
mFiles = [dir('*.m');dir(fullfile('private','*.m'))];
analyzerCount = 0;
for index = 1:numel(mFiles)
    issues = checkcode(fullfile(mFiles(index).folder,mFiles(index).name),'-id');
    if ~isempty(issues)
        fprintf('  Code Analyzer: %s has %d issue(s).\n', ...
            mFiles(index).name,numel(issues));
    end
    analyzerCount = analyzerCount+numel(issues);
end
assert(analyzerCount == 0,'Code Analyzer reported %d issue(s).',analyzerCount);
passed(18) = true;
fprintf('  PASS  %s\n',testNames{18});

summary = struct('packageVersion','3.1.0', ...
    'matlabVersion',version,'moduleDirectory',moduleDirectory, ...
    'testNames',{testNames},'passed',passed,'allPassed',all(passed), ...
    'pweTmmErrorNormalized',pweTmmError, ...
    'fdtdEnergyDrift',energyDrift, ...
    'finitePacketErrorNormalized',packetError, ...
    'blochErrorNormalized',blochError);
summary.crowPweTmmErrorNormalized = crowSpectralError;
summary.crowLossLedgerResidual = ledgerResidual;
summary.finiteBulkDynamicErrors = dynamicErrors;
fprintf('Transmission-line validation passed: %d/%d tests.\n', ...
    sum(passed),numel(passed));
clear cleanupDirectory;
end

% -------------------------------------------------------------------------
function assert_relative(actual,expected,tolerance,label)
errorValue = abs(actual-expected)/max(abs(expected),realmin);
assert(errorValue <= tolerance,'%s relative error %.3g exceeds %.3g.', ...
    label,errorValue,tolerance);
end

function errorValue = spectral_set_error(actual,expected,Omega)
assert(isequal(size(actual),size(expected)));
errorValue = 0;
for index = 1:size(actual,2)
    nMode = size(actual,1);
    permutations = perms(1:nMode);
    best = Inf;
    for candidate = 1:size(permutations,1)
        selected = expected(permutations(candidate,:),index);
        realError = circular_distance(real(actual(:,index)), ...
            real(selected),Omega);
        imagError = abs(imag(actual(:,index))-imag(selected));
        best = min(best,max(hypot(realError,imagError))/Omega);
    end
    errorValue = max(errorValue,best);
end
end

function distance = circular_distance(a,b,period)
distance = abs(mod(a-b+period/2,period)-period/2);
end

function folded = fold_frequency(omega,Omega)
folded = mod(real(omega)+Omega/2,Omega)-Omega/2+1i*imag(omega);
end

function errors = dynamic_circuit_errors()
errors = zeros(3,2);
for circuit = 1:3
    cfg = struct('topology','crow','allowAssumptions',true,'cellCount',12, ...
        'a',7e-3,'Ls',90e-9,'mutualS',7e-9,'C0',22e-12,'Cpar',1e-12, ...
        'deltaC',3e-12,'fmHz',620e6,'L0',13e-9,'Cblock',150e-12, ...
        'Rs',0.2,'Gp',1e-4,'R0',0.4);
    if circuit == 1
        cfg.topology = 'sspp';
    elseif circuit == 2
        cfg.Cblock = Inf;
    end
    model = tl_build_model(cfg);
    k = 2*pi/(model.cell.a*model.finite.cellCount);
    T = model.modulation.period;
    [~,~,Lk] = model.functions.bulkMatrices(k);
    scales = zeros(model.bulk.stateDimension,1);
    scales(1:2) = [sqrt(model.functions.capacitanceBulk(0));sqrt(Lk)];
    if circuit > 1, scales(3) = sqrt(model.resonator.L0); end
    if circuit == 3, scales(4) = sqrt(model.resonator.Cblock); end
    initial = scales.*(1:numel(scales)).';
    reference = tl_tmm_bands(model,k,struct('temporalSlices',4096));
    target = reference.U*initial;
    phase = exp(1i*k*model.cell.a*(0:model.finite.cellCount-1)).';
    for refinement = 1:2
        steps = 128*refinement;
        dt = T/steps;
        half = expm(-model.functions.bulkStateMatrix(k,0)*dt/2)*initial;
        fdtdCfg = struct('dt',dt,'nSteps',steps,'boundaryType','periodic', ...
            'Q0',initial(1)*phase,'IHalf0',half(2)/Lk*phase);
        if circuit > 1
            fdtdCfg.I0Half0 = half(3)/model.resonator.L0*phase;
        end
        if circuit == 3, fdtdCfg.Qblock0 = initial(4)*phase; end
        field = tl_fdtd1d(model,fdtdCfg);
        state = zeros(size(initial));
        state(1) = mean(field.node.Q(end,:)./phase.');
        state(2) = Lk*mean(field.branch.IAtNodeTime(end,:)./phase.');
        if circuit > 1
            state(3) = model.resonator.L0* ...
                mean(field.resonator.IAtNodeTime(end,:)./phase.');
        end
        if circuit == 3
            state(4) = mean(field.resonator.Qblock(end,:)./phase.');
        end
        errors(circuit,refinement) = norm((state-target)./scales)/norm(target./scales);
    end
end
end
